#pragma config(Sensor, in1,    LeftOrRight,    sensorPotentiometer)
#pragma config(Motor,  port2,           LeftWheels,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           RightWheels,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           Scissor,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           ScissorSlave,  tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           LeftClaw,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           RightClaw,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// UNCOMMENT NEXT LINE FOR COMPETITIONS
// COMMENT OUT MAIN FOR COMPETITIONS
//*
#pragma platform(VEX2)
#pragma competitionControl(Competition)
#include "Vex_Competition_Includes.c"
//*/
#include "claw.c"
#include "remote.c"
#include "auto.c"
task debug()
{
	while(1)
	{
		//writeDebugStreamLine("Claw 		Motor: %d	Encoder: %d",motor[ClawRotation],nMotorEncoder[ClawRotation]);
		//writeDebugStreamLine("Scissor Motor: %d	Encoder: %d",motor[Scissor],nMotorEncoder[Scissor]);
		sleep(500);
	}
}

void pre_auton() {}


task autonomous()  { auto(); }
task usercontrol() { remote(); }

//task main() { remote(); }
//task main() { auto(); }
