#pragma config(Motor,  port2,           FR,            tmotorVex393_MC29, openLoop)//front right drive wheel
#pragma config(Motor,  port3,           BR,            tmotorVex393_MC29, openLoop)//back right drive wheel
#pragma config(Motor,  port4,           BL,            tmotorVex393_MC29, openLoop, reversed)//back left drive wheel
#pragma config(Motor,  port5,           FL,            tmotorVex393_MC29, openLoop, reversed)//front left drive wheel
#pragma config(Motor,  port6,           CR,            tmotorVex393_MC29, openLoop)//claw rotation pair *************** reverse one of the motors wires so they turn in different directions **********************
#pragma config(Motor,  port7,           CG,            tmotorVex393_MC29, openLoop, reversed)//claw grab
#pragma config(Motor,  port8,           SL,            tmotorVex393_MC29, openLoop)//scissor lift left side pair
#pragma config(Motor,  port9,           SR,            tmotorVex393_MC29, openLoop)//scissor lift right side pair
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// UNCOMMENT NEXT LINE FOR COMPETITIONS
// COMMENT OUT MAIN FOR COMPETITIONS
/*
#pragma platform(VEX2)
#pragma competitionControl(Competition)
#include "Vex_Competition_Includes.c"
//*/
#include "claw.c"
#include "remote.c"

void pre_auton() {}
void auto()
{
	clsetup();
	sleep(1000);
}

task autonomous()  { auto(); }
task usercontrol() { remote(); }

task main() { remote(); }
//task main() { auto(); }
