<<<<<<< HEAD
#pragma config(Sensor, in1,    LeftOrRight,    sensorPotentiometer)
#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    RightClawRot,   sensorPotentiometer)
#pragma config(Sensor, in2,    LeftClawRot,    sensorPotentiometer)
#pragma config(Sensor, I2C_1,  Scissor,        sensorQuadEncoderOnI2CPort,    , AutoAssign )
=======
#pragma config(Sensor, in1,    RightClawRot,   sensorPotentiometer)
#pragma config(Sensor, in2,    LeftClawRot,    sensorPotentiometer)
#pragma config(Sensor, dgtl6,  ScissorDownS,   sensorTouch)
>>>>>>> parent of b43e24b... Raymond's ready for Hey-Day!
#pragma config(Motor,  port1,           RightClawSlave, tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           LeftWheels,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           RightWheels,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           Scissor,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           ScissorSlave,  tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           LeftClaw,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           RightClaw,     tmotorVex393_MC29, openLoop)
<<<<<<< HEAD
=======
#pragma config(Motor,  port10,          LeftClawSlave, tmotorVex393_HBridge, openLoop, reversed)
>>>>>>> parent of b43e24b... Raymond's ready for Hey-Day!
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// UNCOMMENT NEXT LINE FOR COMPETITIONS
// COMMENT OUT MAIN FOR COMPETITIONS
//*
#pragma platform(VEX2)
#pragma competitionControl(Competition)
#include "Vex_Competition_Includes.c"
//*/
#include "claw.c"
#include "remote.c"
#include "auto.c"
task debug()
{
	while(1)
	{
<<<<<<< HEAD
		//writeDebugStreamLine("Claw 		Motor: %d	Encoder: %d",motor[ClawRotation],nMotorEncoder[ClawRotation]);
		//writeDebugStreamLine("Scissor Motor: %d	Encoder: %d",motor[Scissor],nMotorEncoder[Scissor]);
=======
		writeDebugStreamLine("ScissorEncoder: ", nMotorEncoder[Scissor]);

>>>>>>> parent of b43e24b... Raymond's ready for Hey-Day!
		sleep(500);
	}
}

void pre_auton() {}


task autonomous()  { auto(); }
task usercontrol() { remote(); }

//task main() { remote(); }
//task main() { auto(); }
